---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: tenant-a
  namespace: tenant-a
  labels:
    acm-app: tenant-a
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      acm-app: tenant-a
