---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  namespace: tenant-a-ch-helm
  name: channel
  labels:
    acm-app: tenant-a
spec:
  pathname: https://charts.bitnami.com/bitnami
  type: HelmRepo
