---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: tenant-a
  namespace: tenant-a
  labels:
    acm-app: tenant-a
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  channel: tenant-a-ch-git/channel
  placement:
    local: true
